/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Root */
    get: operations['read_root__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bootstrap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Bootstrap Data
     * @description Fetches the 'Brain' configs and the exercise library.
     *     This allows the frontend to cache the rules on app launch.
     */
    get: operations['get_bootstrap_data_bootstrap_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/state': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User State
     * @description Fetches the user's current progression state and formats it as a View Model
     *     for the Homescreen. Performs datetime calculations on the backend.
     */
    get: operations['get_user_state_user_state_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sessions/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Workout Session
     * @description The core generation endpoint.
     */
    post: operations['generate_workout_session_sessions_generate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sessions/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Session
     * @description Creates a new session record. Evaluates readiness against the Brain
     *     to securely determine the session archetype.
     */
    post: operations['start_session_sessions_start_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sessions/{session_id}/sets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log Atomic Set
     * @description Logs a single set immediately to the database.
     */
    post: operations['log_atomic_set_sessions__session_id__sets_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sessions/{session_id}/complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete Session
     * @description Finalizes the session and securely updates the UTC timestamp for the anchor pattern.
     */
    post: operations['complete_session_sessions__session_id__complete_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/coach-message': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Coach Message
     * @description Fetches a dynamic AI-generated hype message based on the user's training context.
     *     Falls back gracefully on timeout or validation failure.
     */
    get: operations['get_coach_message_user_coach_message_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AIResponse */
    AIResponse: {
      /** Message */
      message: string;
    };
    /** CompleteSessionRequest */
    CompleteSessionRequest: {
      /** Exercise Notes */
      exercise_notes?: {
        [key: string]: string;
      };
      /** Summary Notes */
      summary_notes?: string | null;
      /** Anchor Pattern */
      anchor_pattern?: string | null;
      /** Completed Conditioning Protocol */
      completed_conditioning_protocol?: string | null;
    };
    /** GenerateSessionRequest */
    GenerateSessionRequest: {
      /** Knee Pain */
      knee_pain: number;
      /** Energy */
      energy: number;
      /** Last Trained */
      last_trained?: {
        [key: string]: string | null;
      };
      /** Conditioning Levels */
      conditioning_levels?: {
        [key: string]: number;
      };
      /** Benchmarks */
      benchmarks?: {
        [key: string]: unknown;
      };
    };
    /** GeneratedBlock */
    GeneratedBlock: {
      /** Type */
      type: string;
      /** Label */
      label: string;
      /** Exercises */
      exercises: components['schemas']['GeneratedExercise'][];
    };
    /** GeneratedExercise */
    GeneratedExercise: {
      /** Name */
      name: string;
      /** Is Unilateral */
      is_unilateral: boolean;
      /** Load Type */
      load_type: string;
      /** Tracking Unit */
      tracking_unit: string;
      /** Is Conditioning */
      is_conditioning?: boolean | null;
      /** Description */
      description?: string | null;
      /** Protocol */
      protocol?: string | null;
      /** Rounds */
      rounds?: number | null;
      /** Work Seconds */
      work_seconds?: number | null;
      /** Rest Seconds */
      rest_seconds?: number | null;
      /**
       * Is Benchmark
       * @default false
       */
      is_benchmark: boolean;
      /** Target Intensity */
      target_intensity?: number | string | null;
    };
    /** GeneratedSessionResponse */
    GeneratedSessionResponse: {
      metadata: components['schemas']['SessionMetadata'];
      /** Blocks */
      blocks: components['schemas']['GeneratedBlock'][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LogSetRequest */
    LogSetRequest: {
      /** Exercise Name */
      exercise_name: string;
      /** Set Index */
      set_index: number;
      /** Weight */
      weight?: number | null;
      /** Reps */
      reps?: number | null;
      /** Seconds */
      seconds?: number | null;
      /**
       * Is Warmup
       * @default false
       */
      is_warmup: boolean;
      /**
       * Is Benchmark
       * @default false
       */
      is_benchmark: boolean;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
    };
    /** PatternState */
    PatternState: {
      /** Last Trained Datetime */
      last_trained_datetime: string | null;
      /** Days Since */
      days_since: number | null;
      /** Status Text */
      status_text: string;
      /** Days Since Text */
      days_since_text: string;
    };
    /** SessionMetadata */
    SessionMetadata: {
      /**
       * State
       * @enum {string}
       */
      state: 'GREEN' | 'ORANGE' | 'RED';
      /** Archetype */
      archetype: string;
      /** Anchor Pattern */
      anchor_pattern: string;
      /** State Display Text */
      state_display_text: string;
    };
    /** StartSessionRequest */
    StartSessionRequest: {
      /** Readiness */
      readiness: {
        [key: string]: number;
      };
    };
    /** UserStateResponse */
    UserStateResponse: {
      /** Patterns */
      patterns: {
        [key: string]: components['schemas']['PatternState'];
      };
      /** Conditioning Levels */
      conditioning_levels: {
        [key: string]: number;
      };
      /** Readiness Headline */
      readiness_headline: string;
      /** Readiness Summary Text */
      readiness_summary_text: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  read_root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  get_bootstrap_data_bootstrap_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_user_state_user_state_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserStateResponse'];
        };
      };
    };
  };
  generate_workout_session_sessions_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GenerateSessionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GeneratedSessionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_session_sessions_start_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StartSessionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  log_atomic_set_sessions__session_id__sets_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LogSetRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  complete_session_sessions__session_id__complete_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompleteSessionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_coach_message_user_coach_message_get: {
    parameters: {
      query: {
        local_hour: number;
        local_day?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AIResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
