"""Initial schema

Revision ID: 99b9af15dd9f
Revises: 
Create Date: 2026-01-20 10:24:54.031204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99b9af15dd9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyreadiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('knee_pain', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('computed_state', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_readiness_user_date')
    )
    op.create_index(op.f('ix_dailyreadiness_user_id'), 'dailyreadiness', ['user_id'], unique=False)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('modality', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=True)
    op.create_table('workoutsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('archetype_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workoutsession_user_id'), 'workoutsession', ['user_id'], unique=False)
    op.create_table('workoutset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_order', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('superset_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workoutsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workoutset')
    op.drop_index(op.f('ix_workoutsession_user_id'), table_name='workoutsession')
    op.drop_table('workoutsession')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_dailyreadiness_user_id'), table_name='dailyreadiness')
    op.drop_table('dailyreadiness')
    # ### end Alembic commands ###
